
version: '3.2'

services:
  base_calculation_module:
    build:
      context: ./cm
      dockerfile: Dockerfile
    expose:
      - 80
    stop_signal: SIGKILL
    stdin_open: true
    tty: true
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    command: bash -c "sh app/api_v1/my_calculation_module_directory/CM/helper_functions/cyf/compile_cython.sh && python3 test.py"


